# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "arvados-keep-proxy"
  labels:
    app: arvados-keep-proxy
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvados-keep-proxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-keep-proxy
        release: {{ .Release.Name }}
    spec:
      replicas: 1
      containers:
        - name: arvados-keep-proxy
          image: "cure/arvados-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "/usr/local/bin/bootstrap.sh keepproxy={{ .Values.arvados.versions.distribution.keepProxy }} && keepproxy"
          env:
            - name : ARVADOS_API_HOST
              value: "{{ .Values.externalIP }}:444"
            - name : ARVADOS_API_HOST_INSECURE
              value: "true"
            - name : ARVADOS_API_TOKEN
              value: "thisisnotaverygoodanonymoussecretstring00000000000"
