# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "arvados-keep-web"
  labels:
    app: arvados-keep-web
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvados-keep-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-keep-web
        release: {{ .Release.Name }}
    spec:
      replicas: 1
      containers:
        - name: arvados-keep-web
          image: "cure/arvados-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            # TODO: the apt-get update should be run in the Dockerfile
            - "apt-get update && /usr/local/bin/bootstrap.sh keep-web=1.1.3.20180404192345* && keep-web -listen=:9002 -trust-all-content"
          env:
            - name : ARVADOS_API_HOST
              value: "8.8.8.8:444"
            - name : ARVADOS_API_HOST_INSECURE
              value: "true"
            - name : ARVADOS_API_TOKEN
              value: "thisisnotaverygoodanonymoussecretstring00000000000"
