# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Copy this file to application.yml and edit to suit.
#
# Consult application.default.yml for the full list of configuration
# settings.
#
# The order of precedence is:
# 1. config/environments/{RAILS_ENV}.rb (deprecated)
# 2. Section in application.yml corresponding to RAILS_ENV (e.g., development)
# 3. Section in application.yml called "common"
# 4. Section in application.default.yml corresponding to RAILS_ENV
# 5. Section in application.default.yml called "common"

development:
  # At minimum, you need a nice long randomly generated secret_token here.
  secret_token: ~

  # You probably also want to point to your API server.
  arvados_login_base: https://arvados.local:3030/login
  arvados_v1_base: https://arvados.local:3030/arvados/v1
  arvados_insecure_https: true

  # You need to configure at least one of these:
  keep_web_url: false
  keep_web_download_url: false

production:
  # At minimum, you need a nice long randomly generated secret_token here.
  secret_token: 69f1fd650250e925cb1d9428094add92

  # You probably also want to point to your API server.
  arvados_login_base: https://8.8.8.8:444/login
  arvados_v1_base: https://8.8.8.8:444/arvados/v1
  arvados_insecure_https: true # TODO: Change this to false.

  # You need to configure at least one of these:
  keep_web_url: https://8.8.8.8:9002/c=%{uuid_or_pdh}
  keep_web_download_url: https://8.8.8.8:9002/c=%{uuid_or_pdh}
  trust_all_content: true # TODO: remove this.
